# Generated by Django 5.0.2 on 2025-06-18 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('people', models.ManyToManyField(blank=True, related_name='conversation_people', to='user_app.profile')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversation',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_message', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(blank=True, default=False, null=True)),
                ('is_fav', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_conversation', to='conversation_app.conversation')),
                ('fav_people', models.ManyToManyField(blank=True, related_name='fav_people_message', to='user_app.profile')),
                ('read_people', models.ManyToManyField(blank=True, related_name='read_people_message', to='user_app.profile')),
                ('replied_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_replied', to='conversation_app.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='user_app.profile')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Message',
            },
        ),
    ]
