# Generated by Django 5.0.2 on 2025-06-18 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_app', '0002_remove_message_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='replied_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_replied', to='conversation_app.message'),
        ),
    ]
